app:
  build: .
  command: python3 app.py
  ports:
    - "5001:5001"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:4.4
  hostname: localhost
  environment:
    - MONGO_INITDB_DATABASE=TIWAP
    - MONGO_INITDB_ROOT_USERNAME=username
    - MONGO_INITDB_ROOT_PASSWORD=password
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:27017
